# MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: comtily
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
# Postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: comtily
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi